version: '3.8'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - COMPOSE_FILE_NAME=good-docker-compose.yml
      - SECRET_KEY_FILE=/run/secrets/secret_key
    secrets:
      - secret_key
    volumes:
      - ./data:/app/data:ro
    command: python app.py
    restart: unless-stopped
    user: "1000:1000"

secrets:
  secret_key:
    file: ./secret.txt